# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='neighborhood_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Location'),
        ),
    ]
