# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_neighbourhood_neighborhood_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='neighborhood_name',
            new_name='neighbourhood_name',
        ),
    ]
