# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0008_auto_20190114_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_location',
        ),
    ]
