# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0009_remove_business_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
