# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0010_business_business_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_location',
        ),
    ]
